version: "3"
services:
  react-app:
    image: react-app
    build: ./client/
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: api-server
    build: ./server/
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
